import os 
import json
import pandas as pd

from elasticsearch import Elasticsearch
from shared.config_loader import load_environment

load_environment()

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.getenv("ELASTIC_PASSWORD")

def get_elastic():
    # Create the client instance
    client = Elasticsearch(
        "https://localhost:9200",
        ca_certs="certs/ca/ca.crt",
        basic_auth=("elastic", ELASTIC_PASSWORD)
    )

    match_query = {
        "query": {"match": {"message": "ml-logger -"}}
    }

    # Successful response!
    # client.info()
    # {'name': 'instance-0000000000', 'cluster_name': ...}
    # query = {"query": {"range": {"timestamp": {"gte": "now1d/d"}}}}
    resp = client.search(index="*logstash*", body=match_query)
    # print(resp)
    hits = [(h['_source']['message']) for h in resp['hits']['hits']]
    input_hits = []
    pred_hits = []
    for h in hits:
        if (h.find('ml-logger - INFO - User activity |')!= -1 and h.find('error') == -1):
            input_js = json.loads(h.split('ml-logger - INFO - User activity |')[1])
            input_hits.append(input_js['features'])
            pred_hits.append(input_js['predictions'])
    df = pd.DataFrame(input_hits)
    df['Result'] = pred_hits
    # df.insert(loc=0, column='id', value=range(0, len(df)))
    df = df.rename_axis(index='id')
    df['AnnualPremium'] = df['AnnualPremium'].astype('str')
    # df = df.reset_index(drop=True)
    return df
    # print(df.head)
    # if len(hits) == 0:
    #     print('No production logs found')
# exit(0)

if __name__ == "__main__":
    df = get_elastic()
    print(df)

# prod_df = pd.json_normalize(hits)
