input {
    beats {
        # host => "0.0.0.0"
        port => 5400
        # ssl => false
        #ssl_certificate_authorities => ["/usr/share/logstash/config/certs/ca/ca.crt"]
        #ssl_certificate => "/usr/share/logstash/config/certs/logstash/logstash.crt"
        #ssl_key => "/usr/share/logstash/config/certs/logstash/logstash.key"
    }
}

filter {
  json {
    source => "message"
    skip_on_invalid_json => true
  }
  mutate {
    remove_field => ["service"]
  }
}

output {
 elasticsearch {
   index => "logstash-%{+YYYY.MM.dd}"
   hosts=> "${ELASTIC_HOSTS}"
   user=> "${ELASTIC_USER}"
   password=> "${ELASTIC_PASSWORD}"
   cacert=> "/usr/share/logstash/config/certs/ca/ca.crt"
 }
}
